Artifical Neural Network

In [ ]:
## Importing the Libraries 
import numpy as np
import pandas as pd
import tensorflow as tf 

In [ ]:
tf.__version__

'2.12.0'

In [ ]:
## Data PreProcessing 
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X= dataset.iloc[:,:-1].values # Matrix of Features 
y= dataset.iloc[:,-1].values # Dependent Variable 

In [ ]:
print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [ ]:
# Splitting the dataset into the Training set and Test set  (psytic learn)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

Part 2- Building the ANN 

In [ ]:
#Initializing the ANN 
ann = tf.keras.models.Sequential()

In [ ]:
# Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [ ]:
# Adding the second Hidden layer 
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [ ]:
# Adding the output layer 
ann.add(tf.keras.layers.Dense(units=1))

Part 3- Training the ANN

In [ ]:
# Compiling the ANN 
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

In [ ]:
# Training the ANN model on the Training Set
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 2s 2ms/step - loss: 99735.8828
Epoch 2/100
240/240 [==============================] - 0s 2ms/step - loss: 122.5561
Epoch 3/100
240/240 [==============================] - 0s 2ms/step - loss: 110.1743
Epoch 4/100
240/240 [==============================] - 0s 2ms/step - loss: 108.1713
Epoch 5/100
240/240 [==============================] - 0s 2ms/step - loss: 106.0995
Epoch 6/100
240/240 [==============================] - 0s 2ms/step - loss: 104.0624
Epoch 7/100
240/240 [==============================] - 0s 2ms/step - loss: 102.2109
Epoch 8/100
240/240 [==============================] - 0s 2ms/step - loss: 100.3028
Epoch 9/100
240/240 [==============================] - 0s 2ms/step - loss: 98.2430
Epoch 10/100
240/240 [==============================] - 0s 2ms/step - loss: 96.2075
Epoch 11/100
240/240 [==============================] - 0s 2ms/step - loss: 93.8324
Epoch 12/100
240/240 [==============================] - 0s 2ms/step - loss:

In [ ]:
# Predicting the results of the Test Set 
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

60/60 [==============================] - 0s 1ms/step
[[433.88 431.23]
 [463.06 460.01]
 [467.62 461.14]
 ...
 [474.81 473.26]
 [439.45 438.  ]
 [459.96 463.28]]
